'use client';

import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export function DownloadSummaryButton({
    title,
    summary_text,
    file_name,
    created_at
} : {
    title: string;
    summary_text: string;
    file_name: string;
    created_at: string;
}) {

    const handleDownload = () => {
        const summaryContent = `# ${title}

Generated Summary  
Generated on: ${new Date(created_at).toLocaleDateString()}

        ${summary_text}

Original File: ${file_name}  
Generated by Concise.ai
`;

        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return (
        <Button size="sm" className="h-8 px-3 bg-orange-100 text-orange-600 
        hover:text-orange-700 hover:bg-orange-50" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" />
            Download Summary
        </Button>
    )
}